# Generated by Django 6.0.6 on 2026-06-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('temp_c', models.FloatField()),
                ('feels_like_c', models.FloatField()),
                ('condition_main', models.CharField(max_length=50)),
                ('condition_description', models.CharField(max_length=120)),
                ('is_rainy', models.BooleanField(default=False)),
                ('is_snowy', models.BooleanField(default=False)),
                ('wind_speed', models.FloatField(default=0)),
                ('raw_response', models.JSONField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['city', 'fetched_at'], name='weather_wea_city_8a0d30_idx')],
            },
        ),
    ]
