# Generated by Django 6.0.6 on 2026-06-21 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('warmth_relevant', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='ClothingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='wardrobe/%Y/%m/')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(blank=True, max_length=30)),
                ('warmth_level', models.PositiveSmallIntegerField(choices=[(1, 'Light'), (2, 'Medium'), (3, 'Warm'), (4, 'Very warm')], default=2)),
                ('is_waterproof', models.BooleanField(default=False)),
                ('season', models.CharField(choices=[('all', 'All season'), ('summer', 'Summer'), ('winter', 'Winter'), ('spring_fall', 'Spring/Fall')], default='all', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='wardrobe.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wardrobe_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
